### PR TITLE
Map SQL Server Clob (ntext, text, clob) to 2 mb varchar

### PR DESCRIPTION
**Pull request by Sargul**
see community issue [https://www.exasol.com/portal/questions/46760256/sql-server-ntext-converted-to-varchar4000-in-virtual-schema](https://www.exasol.com/portal/questions/46760256/sql-server-ntext-converted-to-varchar4000-in-virtual-schema)

### CODE REVIEW

**Comment by Sargul** [comment]
Travis failed because of:
Unable to execute SonarQube: Fail to get bootstrap index from server: Failed to connect to localhost/127.0.0.1:9000: Connection refused (Connection refused) -> [Help 1]

There nothing I can do about this. Any suggestions?

**Comment by snehlsen** [comment]
Looks like a transient failure, I restarted the CI build.

**Comment by redcatbear** [comment]
Restarted build.

**Comment by redcatbear** [comment]
Unfortunately Sonar only works from project internal pull request. If you fork to your private repository and then create a PR, Sonar refuses to work.

**Comment by redcatbear** [comment]
@Sargul, please

1. increment the last digit of the version number in the property `<product.version>1.8.2</product.version>` in `virtual-schemas/jdbc-adapter/pom.xml`. 
1. run
   ```bash
   jdbc-adapter/tools/version.sh unify
   ```
1. Commit new version to your branch

**Comment by AnastasiiaSergienko** [comment]
Since we update the version in https://github.com/exasol/virtual-schemas/pull/127 to 1.9.0, we merge this now. Will be part of v1.9.0 then.

**Pull request merged**
